project_name: fakelogit

builds:
  - binary: fakelogit
    goos:
      - darwin
      - windows
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=0

snapshot:
  name_template: SNAPSHOT-{{ .Commit }}

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^dev:'
      - 'README'
      - Merge pull request
      - Merge branch
release:
  github:
    owner: kfortney
    name: fakelogit
  name_template: '{{.Tag}}'
